#!/bin/sh
set -e
. ./iso.sh

if [ "$1" = "gdb" ]; then
    FLAGS="-s -S"
else
    FLAGS=""
fi
qemu-system-$(./target-triplet-to-arch.sh $HOST) -cdrom cewmos.iso -d guest_errors -D ~/output.txt $FLAGS -no-reboot
